# Generated by Django 4.2.4 on 2023-08-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='car_id',
        ),
    ]
