# Generated by Django 4.2.4 on 2023-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_inquiry_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='car_id',
            field=models.IntegerField(default=0),
        ),
    ]
