# Generated by Django 4.2.4 on 2023-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_id',
            field=models.IntegerField(default=0),
        ),
    ]
